export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const DATA_USER = 'DATA_USER';

//Doctor
export const GET_ALL_DOCTOR_START = 'GET_ALL_DOCTOR_START';
export const GET_ALL_DOCTOR_SUCCESS = 'GET_ALL_DOCTOR_SUCCESS';
export const GET_ALL_DOCTOR_FAIL = 'GET_ALL_DOCTOR_FAIL';
//Department
export const GET_ALL_DEPARTMENT_START = 'GET_ALL_DEPARTMENT_START';
export const GET_ALL_DEPARTMENT_SUCCESS = 'GET_ALL_DEPARTMENT_SUCCESS';
export const GET_ALL_DEPARTMENT_FAIL = 'GET_ALL_DEPARTMENT_FAIL';

//Diseases

export const GET_ALL_DISEASES_START = 'GET_ALL_DISEASES_START';
export const GET_ALL_DISEASES_SUCCESS = 'GET_ALL_DISEASES_SUCCESS';
export const GET_ALL_DISEASES_FAIL = 'GET_ALL_DISEASES_FAIL';

//Position
export const GET_ALL_POSITION_START = 'GET_ALL_POSITION_START';
export const GET_ALL_POSITION_SUCCESS = 'GET_ALL_POSITION_SUCCESS';
export const GET_ALL_POSITION_FAIL = 'GET_ALL_POSITION_FAIL';
